LOCAL_PATH := $(call my-dir)
TA_UUID := 5f440c5c-87cc-4e97-9632-74e40a194a1f
TA_SUFFIX := .ta

ifneq ($(filter $(PLATFORM_TDK_VERSION),38 318),)
	ifeq ($(BOARD_AML_SOC_TYPE),)
		LOCAL_TA := v3/signed/$(TA_UUID)$(TA_SUFFIX)
	else
		LOCAL_TA := v3/dev/$(BOARD_AML_SOC_TYPE)/$(TA_UUID)$(TA_SUFFIX)
	endif

	include $(CLEAR_VARS)
	LOCAL_SRC_FILES := $(LOCAL_TA)
	LOCAL_MODULE := $(TA_UUID)
	LOCAL_LICENSE_KINDS := SPDX-license-identifier-Apache-2.0
	LOCAL_LICENSE_CONDITIONS := notice
	LOCAL_MODULE_SUFFIX := $(TA_SUFFIX)
	LOCAL_STRIP_MODULE := false
	LOCAL_MODULE_CLASS := SHARED_LIBRARIES
	LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/lib/teetz
	include $(BUILD_PREBUILT)

	include $(CLEAR_VARS)
	LOCAL_MODULE := tee_fvp_ta
	LOCAL_LICENSE_KINDS := SPDX-license-identifier-Apache-2.0
	LOCAL_LICENSE_CONDITIONS := notice
	LOCAL_MODULE_TAGS := optional
	LOCAL_MODULE_CLASS := SHARED_LIBRARIES
	LOCAL_REQUIRED_MODULES := $(TA_UUID)
	include $(BUILD_PHONY_PACKAGE)

endif
